// Generated by Scripts/generate-icon.sh from Resources/MenuBarIcon.svg. Do not edit by hand.

/// A monochrome PDF template image (only its alpha channel is used, so AppKit tints it to match
/// the light or dark menu bar), embedded as base64 so the menu bar icon needs no resource bundle.
enum MenuBarIconData {
  static let pdfBase64 =
    "JVBERi0xLjcKJbXtrvsKNCAwIG9iago8PCAvTGVuZ3RoIDUgMCBSCiAgIC9GaWx0ZXIgL0ZsYXRl"
    + "RGVjb2RlCj4+CnN0cmVhbQp4nH1OywrCQAy85yvmB4zJPur6BYLgoXoUD6IgiD0UD/6+Md2qIJVl"
    + "hzxmMqMQezM10MgZp456Eh9uV5gfBZc7KYdFxoMUa/tX2h8gLDhTwgY91OkDmj5yNPaSDToMTeaQ"
    + "ccMOLf3QG/6wvY4vmCCrsIY3vXb/rgeWJtjdbDimSVzcIXFTSt1NyDOnWMxAXF7jRVcXHw6rCXXh"
    + "oh/zmnZ0V/Xb3/YtPQHE8U8SCmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iagogICAxNzIKZW5kb2Jq"
    + "CjMgMCBvYmoKPDwKICAgL0V4dEdTdGF0ZSA8PAogICAgICAvYTAgPDwgL0NBIDEgL2NhIDEgPj4K"
    + "ICAgPj4KPj4KZW5kb2JqCjcgMCBvYmoKPDwgL1R5cGUgL09ialN0bQogICAvTGVuZ3RoIDggMCBS"
    + "CiAgIC9OIDEKICAgL0ZpcnN0IDQKICAgL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnic"
    + "M1Mw4IrmiuUCAAY4AV0KZW5kc3RyZWFtCmVuZG9iago4IDAgb2JqCiAgIDE2CmVuZG9iago5IDAg"
    + "b2JqCjw8IC9UeXBlIC9PYmpTdG0KICAgL0xlbmd0aCAxMiAwIFIKICAgL04gNAogICAvRmlyc3Qg"
    + "MjMKICAgL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCnicVZFBa4QwEIXv+RVzKVUKmhi1"
    + "yyJ7WIWllIK4vZUeQhzcQDGSxNL990103VICA/MxL+8Nw4ASRqGgJANWMMIY8OeSVBWk79cJIW3F"
    + "gJYAQPqqegsfkAGFDj4XVOt5dMDI4bAoWqP7WaKBSAplNLCE7ZIcootzk92n6UIHI6aLkjbRZojj"
    + "9RuDwik9NsIhRM0+o1lJd1nJypxT/kT5I6XxZvIXCx68ddC3wmDIEZIt4A17JY76x8el/jGeFGvZ"
    + "Yo/OCyzkd8XJ6HmCqgpN6FeXhW7o7KkRo52Cm7xu+AWcmXHraj/V4LeS2J2OAfrUgXdo9WwkWuB3"
    + "z7MXSreGt/4O/xashRNferjt529wW88P/QLapW8qCmVuZHN0cmVhbQplbmRvYmoKMTIgMCBvYmoK"
    + "ICAgMjc4CmVuZG9iagoxMyAwIG9iago8PCAvVHlwZSAvWFJlZgogICAvTGVuZ3RoIDU4CiAgIC9G"
    + "aWx0ZXIgL0ZsYXRlRGVjb2RlCiAgIC9TaXplIDE0CiAgIC9XIFsxIDIgMl0KICAgL1Jvb3QgMTEg"
    + "MCBSCiAgIC9JbmZvIDEwIDAgUgo+PgpzdHJlYW0KeJxjYGD4/5+JgZOBAUQwMTLKMTAwMvADCUYO"
    + "kBg7iJUGIl6AiL8QdYwggpmRuR0oxjyPgQEA3OQF8gplbmRzdHJlYW0KZW5kb2JqCnN0YXJ0eHJl"
    + "Zgo5MjYKJSVFT0YK"
}
