#!/bin/bash
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"

source_svg="Resources/AppIcon.svg"
output_icns="Resources/AppIcon.icns"
menubar_svg="Resources/MenuBarIcon.svg"
menubar_swift="Sources/TouchpadWM/MenuBarIconData.swift"

if ! command -v rsvg-convert >/dev/null 2>&1; then
  echo "ERROR: rsvg-convert is required (e.g. 'brew install librsvg')." >&2
  exit 1
fi

work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT
iconset="$work_dir/AppIcon.iconset"
mkdir -p "$iconset"

# Each entry is "file name" "pixel size" rendered from the single source SVG.
sizes=(
  "icon_16x16.png 16"
  "icon_16x16@2x.png 32"
  "icon_32x32.png 32"
  "icon_32x32@2x.png 64"
  "icon_128x128.png 128"
  "icon_128x128@2x.png 256"
  "icon_256x256.png 256"
  "icon_256x256@2x.png 512"
  "icon_512x512.png 512"
  "icon_512x512@2x.png 1024"
)

for entry in "${sizes[@]}"; do
  name=${entry%% *}
  size=${entry##* }
  rsvg-convert -w "$size" -h "$size" "$source_svg" -o "$iconset/$name"
done

iconutil -c icns "$iconset" -o "$output_icns"

# The menu bar glyph is embedded as a base64 Swift literal rather than an SwiftPM `resources:`
# bundle: SwiftPM's generated Bundle.module accessor looks for the resource bundle at a path
# codesign refuses to seal (directly inside the .app, alongside Contents/, which macOS app
# bundles cannot contain), so a real resource bundle can't survive `codesign`. A compiled-in
# literal has no path to resolve and needs no separate signing.
menubar_pdf="$work_dir/MenuBarIcon.pdf"
rsvg-convert -f pdf -w 18 -h 18 "$menubar_svg" -o "$menubar_pdf"

# Wrapped at 76 columns (well under swift-format's line-length lint) as concatenated literals.
menubar_base64_lines=$(base64 -i "$menubar_pdf" | fold -w 76)

{
  echo "// Generated by Scripts/generate-icon.sh from Resources/MenuBarIcon.svg. Do not edit by hand."
  echo
  echo "/// A monochrome PDF template image (only its alpha channel is used, so AppKit tints it to match"
  echo "/// the light or dark menu bar), embedded as base64 so the menu bar icon needs no resource bundle."
  echo "enum MenuBarIconData {"
  echo "  static let pdfBase64 ="
  first=true
  while IFS= read -r line; do
    if [[ "$first" == true ]]; then
      echo "    \"$line\""
      first=false
    else
      echo "    + \"$line\""
    fi
  done <<<"$menubar_base64_lines"
  echo "}"
} >"$menubar_swift"

echo "$output_icns"
echo "$menubar_swift"
